'use strict';
// Model list for the settings dropdown:
// pinned models are ALWAYS present; the rest come from model-tests.json
// (generated by `npm run test:models`). Falls back to the API list if the file is missing.
const fs = require('fs');
const path = require('path');
const cf = require('./cf-client');

const PINNED = [
  { id: '@cf/qwen/qwen3.8-27b', description: 'Qwen 3.8 27B — vision, reasoning, tool calling (default)' },
  { id: '@cf/qwen/qwen2.5-coder-32b-instruct', description: 'Qwen 2.5 Coder 32B Instruct' },
];

const RESULTS_FILE = path.join(__dirname, '..', 'model-tests.json');

function readResults() {
  try {
    return JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));
  } catch {
    return null;
  }
}

async function getModelList() {
  const pinned = PINNED.map(m => ({ ...m }));
  const seen = new Set(pinned.map(m => m.id));

  // Include mod-registered models first (so they appear prominently)
  let modModels = [];
  try {
    const { providerRegistry } = require('./mods/providers');
    modModels = providerRegistry.listModels()
      .filter(m => !seen.has(m.id))
      .map(m => ({ id: m.id, description: m.description || `via ${m.providerId}` }));
    for (const m of modModels) seen.add(m.id);
  } catch {}

  const results = readResults();
  if (results && Array.isArray(results.available) && results.available.length) {
    const extra = results.available
      .filter(m => !seen.has(m.id) && m.id.startsWith('@cf/'))
      .map(m => ({
        id: m.id,
        description: (m.description || '') + (m.category === 'quota' ? ' (quota-limited today)' : ''),
      }));
    return pinned.concat(modModels).concat(extra);
  }

  try {
    const api = await cf.listTextModels();
    const extra = api.filter(m => !seen.has(m.id) && m.id.startsWith('@cf/'));
    return pinned.concat(modModels).concat(extra);
  } catch {
    return pinned.concat(modModels);
  }
}

module.exports = { getModelList, PINNED, RESULTS_FILE };